### ISSUE TITLE
Can't run after 1.18 update

### ISSUE THREAD

**Issue by rshkarin** [megamarc/TilenginePythonPlatformer#1]
Hi, I have tried to run the current version with the last engine update and got this error:

```
Traceback (most recent call last):
  File "platformer.py", line 7, in <module>
    from tilengine import *
  File "/home/user/Documents/Tilengine/bindings/python/tilengine.py", line 255, in <module>
    _tln = cdll.LoadLibrary("libTilengine.so")
  File "/usr/lib/python2.7/ctypes/__init__.py", line 440, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libTilengine.so: undefined symbol: TLN_SetBitmapPalette
```

I have recompiled the engine from sources and set the correct library paths. However, it didn't help, could you please point what I do wrong?

**Comment by megamarc** [comment]
I'll test on my machine. I don't know why the ctypes module complains about TLN_SetBitmapPalette() because this function has never been used in the python wrapper. I see that your configuration is linux 64 bits with python 2.7, right?

**Comment by rshkarin** [comment]
@megamarc yes, it is Ubuntu 16.04.1 64bit

Now it works, thank you!
